config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :adventures
  devise_for :users
  root to: 'welcome#show'
end

app/models/adventure.rb
# frozen_string_literal: true
class Adventure < ApplicationRecord
  validates :name, presence: true
  mount_uploader :picture, PictureUploader
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/adventures_controller.rb
# frozen_string_literal: true
class AdventuresController < ApplicationController
  def index
    @adventures = Adventure.where(adventure_filter_params).all
  end

  def show
    load_adventure
  end

  def new
    @adventure = Adventure.new
  end

  def edit
    load_adventure
  end

  def create
    @adventure = Adventure.new(adventure_params)
    if @adventure.save
      redirect_to @adventure, notice: 'Adventure was successfully created.'
    else
      render :new
    end
  end

  def update
    load_adventure
    if @adventure.update(adventure_params)
      redirect_to @adventure, notice: 'Adventure was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    load_adventure
    @adventure.destroy
    redirect_to adventures_url, notice: 'Adventure was successfully destroyed.'
  end

  private

  def load_adventure
    @adventure = Adventure.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def adventure_params
    params.require(:adventure).permit(:name, :description, :picture, :achieved)
  end

  def adventure_filter_params
    params.permit(:achieved)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/views/adventures/_form.html.erb
<%= form_for(adventure) do |f| %>
  <% if adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing Adventure</h1>

<%= render 'form', adventure: @adventure %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Adventures</h1>

<div class="row">
  <% @adventures.in_groups_of(3) do |group| %>
    <% group.compact.each do |adventure| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= image_tag adventure.picture_url if adventure.picture.present?%>
          <div class="caption">
            <h4><%= link_to adventure.name, adventure %></h4>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<br>

<%= link_to 'New Adventure', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New Adventure</h1>

<%= render 'form', adventure: @adventure %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>
<% if @adventure.achieved? %>
<div class="alert alert-success">
  <h2>Achieved!</h2>
</div>
<% end %>
<div class="thumbnail">
  <%= image_tag(@adventure.picture_url, width: 500, height: 500) if @adventure.picture.present? %>
      <div class="caption">
        <h3><%= @adventure.name %></h3>
        <%= @adventure.description %>
      </div>
    </div>


<%= link_to 'Edit', edit_adventure_path(@adventure) %> |
<%= link_to 'Achieved', adventure_path(@adventure, adventure: {achieved: true}), method: :put  unless @adventure.achieved? %> |
<%= link_to 'Back', adventures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheAdventureApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container">
          <div class='navbar-text pull-left'>
            <%= link_to'The Adventure App', root_path, class: 'navbar-link' %> |
            <%= link_to 'My Adventures', adventures_path(achieved: false), class: 'navbar-link' if user_signed_in? %> |
            <%= link_to "Achievements", adventures_path(achieved: true), class: 'navbar-link' if user_signed_in? %>
          </div>

          <div class="navbar-text pull-right">
            <% if user_signed_in? %>
              <strong><%= current_user.email %></strong>
              <%= link_to 'Edit profile', edit_user_registration_path, class:'navbar-link' %> |
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:'navbar-link'  %>
            <% else %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link'  %> |
              <%= link_to 'Log in', new_user_session_path, class: 'navbar-link'  %>
            <% end %>
          </div>
        </div>
      </nav>
      <div class="container">
        <%= yield %>
      </div>
      <footer>
        <div class="container">
          The Adventure App 2017
        </div>
      </footer>
  </body>
</html>

app/views/welcome/show.html.erb
<h1>The Adventure App</h1>
<p><h3>Welcome to the Adventure app</h3></p>
<p>Always say your going to take that holiday or go skydiving but never really get down to planning or simply just forgot?
<br />The Adventure App is designed to help you fulfill your bucket list.</p>
<!-- Add a video here of how the app works -->
<p>Creating an account is free so <%= link_to 'sign up', new_user_registration_path %>  today</p>
<!-- Sign up button below this line -->
<p><h2>Living Life Adventurously!</h2></p>